<?php

namespace App\Models\Book;

use App\Models\File;
use App\Models\Image;
use Illuminate\Contracts\Pagination\LengthAwarePaginator;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\Relations\HasOne;
use Illuminate\Support\Carbon;

/**
 * Class Book
 * @package App\Models\Book
 *
 * @property int      $id
 * @property int      $sub_category_id
 * @property int      $image_id
 * @property int      $file_id
 * @property float    $rating
 * @property int      $publish_date
 *
 * @property Carbon   $created_at
 * @property Carbon   $updated_at
 *
 * @property BookInfo $relationBookInfo
 * @property Image    $relationImage
 * @property File     $relationFile
 */
class Book extends Model{
    /**
     * @var string
     */
    protected $table = 'books';

    /**
     * @return Builder
     */
    public static function query(): Builder
    {
        return parent::query(); // TODO: Change the autogenerated stub
    }

    // Related

    /**
     * @return HasMany
     */
    public function relationBookText(): HasMany{
        return $this->hasMany(BookInfo::class, 'book_id', 'id');
    }

    /**
     * @return HasOne
     */
    public function relationImage(): HasOne{
        return $this->hasOne(Image::class, 'id', 'image_id');
    }

    /**
     * @return HasOne
     */
    public function relationFile(): HasOne{
        return $this->hasOne(File::class, 'id', 'file_id');
    }

    // Getters
    /**
     * @return int
     */
    public function getId(): int{
        return $this->id;
    }

    /**
     * @return int
     */
    public function getSubCategoryId(): int{
        return $this->sub_category_id;
    }

    /**
     * @return int
     */
    public function getImageId():int{
        return $this->image_id;
    }

    /**
     * @return int
     */
    public function getFileId():int{
        return $this->file_id;
    }

    /**
     * @return float
     */
    public function getRating(): float{
        return $this->rating;
    }

    /**
     * @return int
     */
    public function getPublishDate(): int{
        return $this->publish_date;
    }

    /**
     * @return Carbon
     */
    public function getCreatedAt(): Carbon{
        return $this->created_at;
    }
}
